"""create job_match_scores table

Revision ID: 6580be27c9bc
Revises: 623e2ed98906
Create Date: 2025-10-30 21:08:23.782500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6580be27c9bc'
down_revision: Union[str, Sequence[str], None] = '623e2ed98906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_scores_id'), 'job_match_scores', ['id'], unique=False)
    # op.alter_column('jobs', 'site',
    #            existing_type=sa.VARCHAR(length=13),
    #            type_=sa.Enum('INDEED', 'LINKEDIN', 'ZIP_RECRUITER', 'GOOGLE', name='sites', native_enum=False, length=50),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('jobs', 'site',
    #            existing_type=sa.Enum('INDEED', 'LINKEDIN', 'ZIP_RECRUITER', 'GOOGLE', name='sites', native_enum=False, length=50),
    #            type_=sa.VARCHAR(length=13),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_job_match_scores_id'), table_name='job_match_scores')
    op.drop_table('job_match_scores')
    # ### end Alembic commands ###
